config/urls.py
import notifications.urls
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token

from students.views import (
    college_classroom_post_comment,
    college_classroom_post_reply,
    college_student,
    college_student_articles,
    college_student_assignments,
    college_student_classroom_give_test,
    college_student_classroom_view_post,
    college_student_reading_materials,
    college_student_submit_assignment,
    college_student_videos,
    college_teacher_student_account,
    delete_comment_or_reply,
)
from teachers.views import (
    college_teacher_classroom,
    college_teacher_classroom_add_post,
    college_teacher_classroom_delete_test,
    college_teacher_classroom_view_test,
    view_assignments_submissions,
    view_test_performance,
    view_tests_submissions,
)

urlpatterns = [
    path(
        "",
        TemplateView.as_view(
            template_name="home/home.html", extra_context={"section": "home"}
        ),
        name="home",
    ),
    path(
        "profile/",
        TemplateView.as_view(template_name="home/profile.html"),
        name="profile",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("schoolz.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("teachers/", include("teachers.urls")),
    path("students/", include("students.urls")),
    url(
        "^inbox/notifications/", include(notifications.urls, namespace="notifications")
    ),
    path(
        "college/teacher/classroom/",
        college_teacher_classroom,
        name="college_teacher_classroom",
    ),
    path(
        "college/teacher/classroom/<int:pk>/add_post",
        college_teacher_classroom_add_post,
        name="college_teacher_classroom_add_post",
    ),
    path(
        "college/teacher/classroom/view_test/<slug:slug_pk>/",
        college_teacher_classroom_view_test,
        name="college_teacher_classroom_view_test",
    ),
    path(
        "college/teacher/classroom/delete_test/<slug:slug_pk>/",
        college_teacher_classroom_delete_test,
        name="college_teacher_classroom_delete_test",
    ),
    path(
        "college/teacher/classroom/view_tests_submissions/",
        view_tests_submissions,
        name="view_tests_submissions",
    ),
    path(
        "college/teacher/classroom/view_assignments_submissions/",
        view_assignments_submissions,
        name="view_assignments_submissions",
    ),
    path(
        "college/teacher/classroom/view_test_performance/<slug:slug_pk>",
        view_test_performance,
        name="view_test_performance",
    ),
    path("college/student", college_student, name="college_student"),
    path(
        "college/student/classroom/college_student_assignments",
        college_student_assignments,
        name="college_student_assignments",
    ),
    path(
        "college/student/classroom/college_student_submit_assignment/<slug:slug_pk>/",
        college_student_submit_assignment,
        name="college_student_submit_assignment",
    ),
    path(
        "college/student/classroom/college_student_reading_materials",
        college_student_reading_materials,
        name="college_student_reading_materials",
    ),
    path(
        "college/student/classroom/college_student_videos",
        college_student_videos,
        name="college_student_videos",
    ),
    path(
        "college/student/classroom/college_student_articles",
        college_student_articles,
        name="college_student_articles",
    ),
    path(
        "college/student/classroom/give_test/<slug:slug_pk>/",
        college_student_classroom_give_test,
        name="college_student_classroom_give_test",
    ),
    path(
        "college/classroom/view_post/<slug:slug_pk>/",
        college_student_classroom_view_post,
        name="college_student_classroom_view_post",
    ),
    path(
        "college/classroom/comment",
        college_classroom_post_comment,
        name="college_classroom_post_comment",
    ),
    path(
        "college/classroom/reply",
        college_classroom_post_reply,
        name="college_classroom_post_reply",
    ),
    path(
        "college/classroom/delete_comment_or_reply/<int:pk>",
        delete_comment_or_reply,
        name="delete_comment_or_reply",
    ),
    path(
        "college/student/college_teacher_student_account",
        college_teacher_student_account,
        name="college_teacher_student_account",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

schoolz/users/urls.py
from django.urls import path

from .views import (
    AdminDetailView,
    AdminSignUpView,
    AdminUpdateView,
    DeleteMessage,
    UpdateMessage,
    admin_dashboard,
    create_codes,
    load_students,
    send_admin_message,
    send_general_message,
    send_messages,
    show_list,
    user_detail_view,
    user_redirect_view,
    user_update_view,
    view_codes,
    view_messages,
)

app_name = "users"

urlpatterns = [
    path("parent/", send_admin_message, name="parent"),
    path("view_codes/", view_codes, name="view_codes"),
    path("create_codes/", create_codes, name="code"),
    path("load_students/", load_students, name="load"),
    path(
        "<slug:slug_pk>/message_edit/", UpdateMessage.as_view(), name="message_update"
    ),
    path(
        "<slug:slug_pk>/message_delete/", DeleteMessage.as_view(), name="message_delete"
    ),
    path("view_messages/", view_messages, name="view_message"),
    path("send_message/", send_messages, name="message"),
    path("send_general_message/", send_general_message, name="general_message"),
    path("show_list/", show_list, name="show_list"),
    path("dashboard/", admin_dashboard, name="dash"),
    path("<slug:uuid_pk>/profile/", AdminDetailView.as_view(), name="admin_detail"),
    path("<slug:uuid_pk>/update/", AdminUpdateView.as_view(), name="admin_update"),
    path("signup/", AdminSignUpView.as_view(), name="admin"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

students/urls.py
from django.urls import path

from .views import (  # search_student,
    StudentAdminSignupView,
    StudentDeleteView,
    StudentProfileView,
    StudentSignupView,
    StudentTeacherUpdateView,
    StudentUpdateView,
    active,
    load_sub_class,
    payment,
    result_pin,
    search_all,
    show_result,
    student_dashboard,
    student_list,
    student_teacher_list,
    view_general_messages,
    view_messages,
)

app_name = "students"

urlpatterns = [
    path("signup/", StudentSignupView.as_view(), name="signup"),
    path("student_signup/", StudentAdminSignupView.as_view(), name="student_signup"),
    path("<slug:uuid_pk>/profile/", StudentProfileView.as_view(), name="profile"),
    path("<slug:uuid_pk>/edit/", StudentUpdateView.as_view(), name="update"),
    path("<slug:uuid_pk>/update/", StudentTeacherUpdateView.as_view(), name="updates"),
    path("<slug:uuid_pk>/delete/", StudentDeleteView.as_view(), name="delete"),
    path("dashboard/", student_dashboard, name="dash"),
    path("student_list/", student_teacher_list, name="student_teacher_list"),
    path("students_list/", student_list, name="student_list"),
    path("show_result/", show_result, name="show_result"),
    path("load_subclass/", load_sub_class, name="load_subclass"),
    path("view_message/", view_messages, name="message"),
    path("general_message/", view_general_messages, name="general_message"),
    path("find/", search_all, name="search_all"),
    path("payment/", payment, name="payment"),
    path("pin/<int:class_id>/<int:session_id>", result_pin, name="pin"),
    path("<slug:uuid_key>/active/", active, name="active"),
]

teachers/urls.py
from django.urls import path

from .views import (
    AdminTeacherUpdateView,
    DeleteMessage,
    TeacherDeleteView,
    TeacherProfileView,
    TeacherSignupView,
    TeacherUpdateView,
    UpdateMessage,
    add_result,
    load_class,
    load_student_result,
    load_sub_class,
    promote_student,
    promote_student_process,
    send_general_message,
    send_messages,
    show_result,
    show_teachers_comment,
    teacher_dashboard,
    teacher_list,
    teachers_comment,
    view_admin_messages,
    view_general_messages,
    view_messages,
)

app_name = "teachers"

urlpatterns = [
    path("<slug:section>/list/", teacher_list, name="list"),
    path("signup/", TeacherSignupView.as_view(), name="signup"),
    path("<slug:uuid_pk>/edit/", TeacherUpdateView.as_view(), name="update"),
    path(
        "<slug:uuid_pk>/admin_edit/",
        AdminTeacherUpdateView.as_view(),
        name="admin_update",
    ),
    path("<slug:uuid_pk>/profile/", TeacherProfileView.as_view(), name="profile"),
    path("<slug:uuid_pk>/delete/", TeacherDeleteView.as_view(), name="delete"),
    path("dashboard/", teacher_dashboard, name="dash"),
    path("add_result/", add_result, name="add_result"),
    path("show_result/", show_result, name="show_result"),
    path("load_subclass", load_sub_class, name="load_subclass"),
    path("load_class", load_class, name="load_class"),
    path("promote/", promote_student, name="promote"),
    path("process/", promote_student_process, name="promote_student"),
    path("send_message/", send_messages, name="message"),
    path("send_general_message/", send_general_message, name="general_message"),
    path("view_messages/", view_messages, name="view_message"),
    path("view_admin_messages/", view_admin_messages, name="view_admin_message"),
    path("view_general_messages/", view_general_messages, name="view_general_message"),
    path(
        "<slug:slug_pk>/message_edit/", UpdateMessage.as_view(), name="message_update"
    ),
    path(
        "<slug:slug_pk>/message_delete/", DeleteMessage.as_view(), name="message_delete"
    ),
    path("teachers_comment/", teachers_comment, name="teachers_comment"),
    path("load_comment", show_teachers_comment, name="load_comment"),
    path("load_student_result", load_student_result, name="load_student_result"),
]

schoolz/users/forms.py
from django import forms as form
from django.contrib.auth import forms
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.db import transaction
from django.utils.translation import gettext_lazy as _

from teachers.models import Section, TeacherMessages

from .models import Admin, AdminModel

User = get_user_model()


class TeacherMessageForm(form.ModelForm):
    class Meta:
        model = TeacherMessages
        exclude = {"admin", "teacher", "updated_at", "created_at", "private", "slug"}
        widgets = {
            "title": form.TextInput(attrs={"class": "form-control"}),
            "messages": form.TextInput(attrs={"class": "form-control"}),
        }


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    error_message = admin_forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])


class AdminSignUpForm(UserCreationForm):
    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )
    name = form.CharField(
        max_length=150, widget=form.TextInput(attrs={"class": "form-control"})
    )
    photo = form.ImageField(
        required=False, widget=form.ClearableFileInput(attrs={"class": "form-control"})
    )
    date_of_birth = form.DateField(
        required=True, widget=form.TextInput(attrs={"type": "date"})
    )
    section = form.ModelChoiceField(queryset=Section.objects.all(), required=True)

    mobile = form.CharField(
        max_length=11,
        required=True,
        widget=form.TextInput(attrs={"class": "form-control"}),
    )

    address = form.CharField(
        max_length=500, widget=form.Textarea(attrs={"class": "form-control"})
    )

    email = form.CharField(
        max_length=255,
        required=True,
        widget=form.TextInput(attrs={"class": "form-control"}),
    )
    joining_date = form.DateField(
        required=True, widget=form.TextInput(attrs={"type": "date"})
    )

    class Meta(UserCreationForm.Meta):
        model = Admin
        fields = UserCreationForm.Meta.fields + ("email",)
        exclude = ["username"]

    def clean_username(self):
        username = self.cleaned_data["username"]
        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.name = self.cleaned_data.get("name")
        user.save()
        admin = AdminModel.objects.create(
            user=user,
            uuid=user.uuid,
            name=self.cleaned_data.get("name"),
            photo=self.cleaned_data.get("photo"),
            date_of_birth=self.cleaned_data.get("date_of_birth"),
            section=self.cleaned_data.get("section"),
            mobile=self.cleaned_data.get("mobile"),
            email=self.cleaned_data.get("email"),
            address=self.cleaned_data.get("address"),
            joining_date=self.cleaned_data.get("joining_date"),
        )
        admin.save()
        return user

schoolz/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False, methods=["GET"])
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

schoolz/templates/base/sidebar.html
{% load static %}
<!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-light-indigo elevation-4">
    <!-- Brand Logo -->
    <a href="" class="brand-link">
      <img src="{% static 'project/AdminLTELogo.png' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text font-weight-light">Admin Dashboard</span>
    </a>

    <!-- Sidebar -->
    {% if request.user.is_admin %}
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{{ request.user.adminmodel.get_photo_url }}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="{% url 'users:dash' %}" class="d-block">Dashboard</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-user-graduate"></i>
              <p>
                Student
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>

            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'students:student_signup' %}" class="nav-link">
                  <i class="fas fa-user-plus nav-icon"></i>
                  <p>Student Registration</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'users:show_list' %}" class="nav-link">
                  <i class="fas fa-list nav-icon"></i>
                  <p>Student List</p>
                </a>
              </li>
            </ul>
          </li>

          <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-chalkboard-teacher"></i>
              <p>
                Teacher
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>

            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'teachers:signup' %}" class="nav-link">
                  <i class="fas fa-user-plus nav-icon"></i>
                  <p>Teacher Registration</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'teachers:list' 'Primary' %}" class="nav-link">
                  <i class="fas fa-list nav-icon"></i>
                  <p>Primary</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'teachers:list' 'Secondary' %}" class="nav-link">
                  <i class="fas fa-list nav-icon"></i>
                  <p>Secondary</p>
                </a>
              </li>
            </ul>
          </li>

          <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-chalkboard-teacher"></i>
              <p>
                Result
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>

            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'users:code' %}" class="nav-link">
                  <i class="fas fa-user-plus nav-icon"></i>
                  <p>Generate Codes</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'users:view_codes' %}" class="nav-link">
                  <i class="fas fa-list nav-icon"></i>
                  <p>View Codes</p>
                </a>
              </li>
            </ul>
          </li>

          <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-envelope"></i>
              <p>
                Message
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>

            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'users:message' %}" class="nav-link">
                  <i class="fas fa-user-plus nav-icon"></i>
                  <p>Send Private Message</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'users:general_message' %}" class="nav-link">
                  <i class="fas fa-list nav-icon"></i>
                  <p>Send General Message</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'users:view_message' %}" class="nav-link">
                  <i class="fas fa-search nav-icon"></i>
                  <p>Sent Messages</p>
                </a>
              </li>
            </ul>
          </li>
        </ul>
      </nav>
    </div>
    <!-- /.sidebar-menu -->

    {% elif request.user.is_teacher %}
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{{ user.teachermodel.get_photo_url }}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="{% url 'teachers:dash' %}" class="d-block">Dashboard</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-user-graduate"></i>
              <p>
                Student
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>

            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'students:signup' %}" class="nav-link">
                  <i class="fas fa-user-plus nav-icon"></i>
                  <p>Student Registration</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'students:student_teacher_list' %}" class="nav-link">
                  <i class="fas fa-list nav-icon"></i>
                  <p>Student List</p>
                </a>
              </li>
            </ul>
          </li>

          <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-chalkboard-teacher"></i>
              <p>
                Result
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>

            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'teachers:add_result' %}" class="nav-link">
                  <i class="fas fa-puzzle-piece nav-icon"></i>
                  <p>Add Result</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'teachers:promote' %}" class="nav-link">
                  <i class="fas fa-user-plus nav-icon"></i>
                  <p>Promote</p>
                </a>
              </li>

              <li class="nav-item">
                <a href="{% url 'teachers:show_result' %}" class="nav-link">
                  <i class="fas fa-puzzle-piece nav-icon"></i>
                  <p>Show Result</p>
                </a>
              </li>
            </ul>
          </li>

          <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-envelope"></i>
              <p>
                Message
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'teachers:message' %}" class="nav-link">
                  <i class="fas fa-envelope nav-icon"></i>
                  <p>Send Private Message</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'teachers:general_message' %}" class="nav-link">
                  <i class="fas fa-envelope nav-icon"></i>
                  <p>Send General Message</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'teachers:view_message' %}" class="nav-link">
                  <i class="fas fa-envelope-open nav-icon"></i>
                  <p>Sent Messages</p>
                </a>
              </li>
            </ul>
          </li>

          <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-envelope-square"></i>
              <p>
                Recieved Messages
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>

            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'teachers:view_admin_message' %}" class="nav-link">
                  <i class="fas fa-envelope-open-text nav-icon"></i>
                  <p>Private</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'teachers:view_general_message' %}" class="nav-link">
                  <i class="fas fa-envelope-open-text nav-icon"></i>
                  <p>General</p>
                </a>
              </li>
            </ul>
          </li>
        </ul>
      </nav>
    </div>
    <!-- /.sidebar-menu -->

    {% else %}
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{{ request.user.studentmodel.get_photo_url }}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="{% url 'students:dash' %}" class="d-block">Dashboard</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-user-graduate"></i>
              <p>
                Student
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>

            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'students:student_list' %}" class="nav-link">
                  <i class="fas fa-list nav-icon"></i>
                  <p>Student List</p>
                </a>
              </li>
            </ul>
          </li>

          <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-chalkboard-teacher"></i>
              <p>
                Teacher
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>

            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'teachers:list' 'Primary' %}" class="nav-link">
                  <i class="fas fa-list nav-icon"></i>
                  <p>Primary</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'teachers:list' 'Secondary' %}" class="nav-link">
                  <i class="fas fa-list nav-icon"></i>
                  <p>Secondary</p>
                </a>
              </li>
            </ul>
          </li>

          <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-book-open"></i>
              <p>
                Result
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>

            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'students:show_result' %}" class="nav-link">
                  <i class="fas fa-puzzle-piece nav-icon"></i>
                  <p>Show Result</p>
                </a>
              </li>
            </ul>
          </li>

          <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-envelope"></i>
              <p>
                Message
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>

            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'students:message' %}" class="nav-link">
                  <i class="fas fa-envelope-open-text nav-icon"></i>
                  <p>Private</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'students:general_message' %}" class="nav-link">
                  <i class="fas fa-envelope-open-text nav-icon"></i>
                  <p>General</p>
                </a>
              </li>
            </ul>
          </li>
        </ul>
      </nav>
    </div>
      {% endif %}
    <!-- /.sidebar-menu -->
    <!-- /.sidebar -->
  </aside>