config/urls.py
import notifications.urls
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token

from students.views import (
    college_classroom_post_comment,
    college_classroom_post_reply,
    college_student,
    college_student_articles,
    college_student_assignments,
    college_student_classroom_give_test,
    college_student_classroom_view_post,
    college_student_reading_materials,
    college_student_submit_assignment,
    college_student_videos,
    college_teacher_student_account,
    delete_comment_or_reply,
)
from teachers.views import (
    college_teacher_classroom,
    college_teacher_classroom_add_post,
    college_teacher_classroom_delete_test,
    college_teacher_classroom_view_test,
    view_assignments_submissions,
    view_test_performance,
    view_tests_submissions,
)

urlpatterns = [
    path(
        "",
        TemplateView.as_view(
            template_name="home/home.html", extra_context={"section": "home"}
        ),
        name="home",
    ),
    path(
        "profile/",
        TemplateView.as_view(template_name="home/profile.html"),
        name="profile",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("schoolz.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("teachers/", include("teachers.urls")),
    path("students/", include("students.urls")),
    url(
        "^inbox/notifications/", include(notifications.urls, namespace="notifications")
    ),
    path(
        "college/teacher/classroom/",
        college_teacher_classroom,
        name="college_teacher_classroom",
    ),
    path(
        "college/teacher/classroom/<int:pk>/add_post",
        college_teacher_classroom_add_post,
        name="college_teacher_classroom_add_post",
    ),
    path(
        "college/teacher/classroom/view_test/<slug:slug_pk>/",
        college_teacher_classroom_view_test,
        name="college_teacher_classroom_view_test",
    ),
    path(
        "college/teacher/classroom/delete_test/<slug:slug_pk>/",
        college_teacher_classroom_delete_test,
        name="college_teacher_classroom_delete_test",
    ),
    path(
        "college/teacher/classroom/view_tests_submissions/",
        view_tests_submissions,
        name="view_tests_submissions",
    ),
    path(
        "college/teacher/classroom/view_assignments_submissions/",
        view_assignments_submissions,
        name="view_assignments_submissions",
    ),
    path(
        "college/teacher/classroom/view_test_performance/<slug:slug_pk>",
        view_test_performance,
        name="view_test_performance",
    ),
    path("college/student", college_student, name="college_student"),
    path(
        "college/student/classroom/college_student_assignments",
        college_student_assignments,
        name="college_student_assignments",
    ),
    path(
        "college/student/classroom/college_student_submit_assignment/<slug:slug_pk>/",
        college_student_submit_assignment,
        name="college_student_submit_assignment",
    ),
    path(
        "college/student/classroom/college_student_reading_materials",
        college_student_reading_materials,
        name="college_student_reading_materials",
    ),
    path(
        "college/student/classroom/college_student_videos",
        college_student_videos,
        name="college_student_videos",
    ),
    path(
        "college/student/classroom/college_student_articles",
        college_student_articles,
        name="college_student_articles",
    ),
    path(
        "college/student/classroom/give_test/<slug:slug_pk>/",
        college_student_classroom_give_test,
        name="college_student_classroom_give_test",
    ),
    path(
        "college/classroom/view_post/<slug:slug_pk>/",
        college_student_classroom_view_post,
        name="college_student_classroom_view_post",
    ),
    path(
        "college/classroom/comment",
        college_classroom_post_comment,
        name="college_classroom_post_comment",
    ),
    path(
        "college/classroom/reply",
        college_classroom_post_reply,
        name="college_classroom_post_reply",
    ),
    path(
        "college/classroom/delete_comment_or_reply/<int:pk>",
        delete_comment_or_reply,
        name="delete_comment_or_reply",
    ),
    path(
        "college/student/college_teacher_student_account",
        college_teacher_student_account,
        name="college_teacher_student_account",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

schoolz/users/urls.py
from django.urls import path

from .views import (
    AdminDetailView,
    AdminSignUpView,
    AdminUpdateView,
    DeleteMessage,
    UpdateMessage,
    admin_dashboard,
    create_codes,
    load_students,
    send_admin_message,
    send_general_message,
    send_messages,
    show_list,
    user_detail_view,
    user_redirect_view,
    user_update_view,
    view_codes,
    view_messages,
)

app_name = "users"

urlpatterns = [
    path("parent/", send_admin_message, name="parent"),
    path("view_codes/", view_codes, name="view_codes"),
    path("create_codes/", create_codes, name="code"),
    path("load_students/", load_students, name="load"),
    path(
        "<slug:slug_pk>/message_edit/", UpdateMessage.as_view(), name="message_update"
    ),
    path(
        "<slug:slug_pk>/message_delete/", DeleteMessage.as_view(), name="message_delete"
    ),
    path("view_messages/", view_messages, name="view_message"),
    path("send_message/", send_messages, name="message"),
    path("send_general_message/", send_general_message, name="general_message"),
    path("show_list/", show_list, name="show_list"),
    path("dashboard/", admin_dashboard, name="dash"),
    path("<slug:uuid_pk>/profile/", AdminDetailView.as_view(), name="admin_detail"),
    path("<slug:uuid_pk>/update/", AdminUpdateView.as_view(), name="admin_update"),
    path("signup/", AdminSignUpView.as_view(), name="admin"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

teachers/urls.py
from django.urls import path

from .views import (
    AdminTeacherUpdateView,
    DeleteMessage,
    TeacherDeleteView,
    TeacherProfileView,
    TeacherSignupView,
    TeacherUpdateView,
    UpdateMessage,
    add_result,
    load_class,
    load_student_result,
    load_sub_class,
    promote_student,
    promote_student_process,
    send_general_message,
    send_messages,
    show_result,
    show_teachers_comment,
    teacher_dashboard,
    teacher_list,
    teachers_comment,
    view_admin_messages,
    view_general_messages,
    view_messages,
)

app_name = "teachers"

urlpatterns = [
    path("<slug:section>/list/", teacher_list, name="list"),
    path("signup/", TeacherSignupView.as_view(), name="signup"),
    path("<slug:uuid_pk>/edit/", TeacherUpdateView.as_view(), name="update"),
    path(
        "<slug:uuid_pk>/admin_edit/",
        AdminTeacherUpdateView.as_view(),
        name="admin_update",
    ),
    path("<slug:uuid_pk>/profile/", TeacherProfileView.as_view(), name="profile"),
    path("<slug:uuid_pk>/delete/", TeacherDeleteView.as_view(), name="delete"),
    path("dashboard/", teacher_dashboard, name="dash"),
    path("add_result/", add_result, name="add_result"),
    path("show_result/", show_result, name="show_result"),
    path("load_subclass", load_sub_class, name="load_subclass"),
    path("load_class", load_class, name="load_class"),
    path("promote/", promote_student, name="promote"),
    path("process/", promote_student_process, name="promote_student"),
    path("send_message/", send_messages, name="message"),
    path("send_general_message/", send_general_message, name="general_message"),
    path("view_messages/", view_messages, name="view_message"),
    path("view_admin_messages/", view_admin_messages, name="view_admin_message"),
    path("view_general_messages/", view_general_messages, name="view_general_message"),
    path(
        "<slug:slug_pk>/message_edit/", UpdateMessage.as_view(), name="message_update"
    ),
    path(
        "<slug:slug_pk>/message_delete/", DeleteMessage.as_view(), name="message_delete"
    ),
    path("teachers_comment/", teachers_comment, name="teachers_comment"),
    path("load_comment", show_teachers_comment, name="load_comment"),
    path("load_student_result", load_student_result, name="load_student_result"),
]

schoolz/users/forms.py
from django import forms as form
from django.contrib.auth import forms
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.db import transaction
from django.utils.translation import gettext_lazy as _

from teachers.models import Section, TeacherMessages

from .models import Admin, AdminModel

User = get_user_model()


class TeacherMessageForm(form.ModelForm):
    class Meta:
        model = TeacherMessages
        exclude = {"admin", "teacher", "updated_at", "created_at", "private", "slug"}
        widgets = {
            "title": form.TextInput(attrs={"class": "form-control"}),
            "messages": form.TextInput(attrs={"class": "form-control"}),
        }


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    error_message = admin_forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])


class AdminSignUpForm(UserCreationForm):
    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )
    name = form.CharField(
        max_length=150, widget=form.TextInput(attrs={"class": "form-control"})
    )
    photo = form.ImageField(
        required=False, widget=form.ClearableFileInput(attrs={"class": "form-control"})
    )
    date_of_birth = form.DateField(
        required=True, widget=form.TextInput(attrs={"type": "date"})
    )
    section = form.ModelChoiceField(queryset=Section.objects.all(), required=True)

    mobile = form.CharField(
        max_length=11,
        required=True,
        widget=form.TextInput(attrs={"class": "form-control"}),
    )

    address = form.CharField(
        max_length=500, widget=form.Textarea(attrs={"class": "form-control"})
    )

    email = form.CharField(
        max_length=255,
        required=True,
        widget=form.TextInput(attrs={"class": "form-control"}),
    )
    joining_date = form.DateField(
        required=True, widget=form.TextInput(attrs={"type": "date"})
    )

    class Meta(UserCreationForm.Meta):
        model = Admin
        fields = UserCreationForm.Meta.fields + ("email",)
        exclude = ["username"]

    def clean_username(self):
        username = self.cleaned_data["username"]
        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.name = self.cleaned_data.get("name")
        user.save()
        admin = AdminModel.objects.create(
            user=user,
            uuid=user.uuid,
            name=self.cleaned_data.get("name"),
            photo=self.cleaned_data.get("photo"),
            date_of_birth=self.cleaned_data.get("date_of_birth"),
            section=self.cleaned_data.get("section"),
            mobile=self.cleaned_data.get("mobile"),
            email=self.cleaned_data.get("email"),
            address=self.cleaned_data.get("address"),
            joining_date=self.cleaned_data.get("joining_date"),
        )
        admin.save()
        return user

schoolz/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False, methods=["GET"])
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

schoolz/templates/users/ASU.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %} Admin {% endblock %}

{% block content %}
  <h1> ADMIN </h1>
  <form class="form-horizontal" method="post" action="{% url 'users:admin' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-secondary">Sign Up</button>
      </div>
    </div>
  </form>
{% endblock %}

schoolz/templates/users/admin_dashboard.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %} School Management System {% endblock title %}

{% block content %}
{% comment %} Display Messages {% endcomment %}
 {% if messages %}
   <div class="form-group">
     <div class="col-12">
       {% for message in messages %}
       {% if message.tags == "error" %}
           <div class="alert alert-default-danger alert-dismissible fade show" role="alert" style="margin-top: 10px;">
           {{ message }}
           <button type="button" class="close" data-dismiss="alert" aria-label="Close">
               <span aria-hidden="true">&times;</span>
           </button>
           </div>
       {% elif message.tags == "success" %}
           <div class="alert alert-default-success alert-dismissible fade show" role="alert" style="margin-top: 10px;">
           {{ message }}
           <button type="button" class="close" data-dismiss="alert" aria-label="Close">
               <span aria-hidden="true">&times;</span>
           </button>
           </div>
       {% endif %}
       {% endfor %}
     </div>
   </div>
 {% endif %}
<div class="animated fadeIn">
    <div class="row">
      <div class="col-lg-3 col-12">
        <!-- small box -->
        <div class="small-box bg-gradient-purple">
          <div class="inner">
            <h3 class="count">{{ student }}</h3>
            <p>Student in {{ section }}</p>
          </div>
          <div class="icon" style="display:block;">
            <i class="fas fa-user-graduate"></i>
          </div>
          <a href="{% url 'users:show_list' %}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
        </div>
      </div>
      <div class="col-lg-3 col-12">
        <!-- small box -->
        <div class="small-box bg-gradient-success">
          <div class="inner">
            <h3 class="count">{{ teacher }}</h3>
            <p>Class Teacher in {{ section }} </p>

          </div>
          <div class="icon" style="display:block;">
            <i class="fas fa-chalkboard-teacher"></i>
          </div>
          <a href="{% url 'teachers:list' section %}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
        </div>
      </div>
      <div class="col-lg-3 col-12">
        <!-- small box -->
        <div class="small-box bg-gradient-warning">
          <div class="inner">
            <h3 class="count" >{{ other_students }}</h3>
            <p>Student in {{ spectre }}</p>
          </div>
          <div class="icon" style="display:block;">
            <i class="fas fa-user-graduate "></i>
          </div>
          <p class="small-box-footer"> <i class="fa fa-puzzle-piece"></i></p>
        </div>
      </div>
      <div class="col-lg-3 col-12">
        <!-- small box -->
        <div class="small-box" style="background-color: #7fc9fb; color: #005ebf">
          <div class="inner">
            <h3 class="count">{{ other_teachers }}</h3>
            <p>Class Teacher in {{ spectre }}</p>
          </div>
          <div class="icon" style="display:block;">
            <i class="fas fa-chalkboard-teacher"></i>
          </div>
          <a href="{% url 'teachers:list' spectre %}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-6 col-12">
        <!-- DONUT CHART -->
        <div class="card">
          <div class="card-header text-white" style="background-color: #f6b0d0;">
            <h3 class="card-title text-purple"> Paid {{ section.sections }} Student Chart</h3>
            <div class="card-tools">
              <button type="button" class="btn btn-tool text-purple" data-card-widget="collapse"><i class="fas fa-minus"></i>
              </button>
              <button type="button" class="btn btn-tool text-purple" data-card-widget="remove"><i class="fas fa-times"></i></button>
            </div>
          </div>
          <div class="card-body">
            <canvas id="donutChart" style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%;"></canvas>
          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
      </div>
      <div class="col-lg-6 col-12">
        <!-- DONUT CHART -->
        <div class="card">
          <div class="card-header text-info" style="background-color: #7fc9fb;">
            <h3 class="card-title">Paid {{ spectre }} Student Chart</h3>
            <div class="card-tools">
              <button type="button" class="btn btn-tool text-info" data-card-widget="collapse"><i class="fas fa-minus"></i>
              </button>
              <button type="button" class="btn btn-tool text-info" data-card-widget="remove"><i class="fas fa-times"></i></button>
            </div>
          </div>
          <div class="card-body">
            <canvas id="donutChart2" style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%;"></canvas>
          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
      </div>
    </div>
</div>
{% endblock %}

{% block writescript %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js" integrity="sha512-s+xg36jbIujB2S2VKfpGmlC3T5V2TF3lY48DX7u2r9XzGzgPsa6wTpOQA7J9iffvdeBN0q9tKzRxVxw1JviZPg==" crossorigin="anonymous"></script>
  <script>
  $(document).ready(function () {

    $(function () {
          //- DONUT CHART -
      //-------------
      // Get context with jQuery - using jQuery's .get() method.
      var donutChartCanvas = $('#donutChart').get(0).getContext('2d')
      var donutData        = {
        labels: [
            'Paid',
            'Not Paid',
        ],
        datasets: [
          {
            data: [{{ paid_students }}, {{ unpaid }}],
            backgroundColor : ['#7fc9fb', '#dc3545'],
          }
        ]
      }
      var donutOptions     = {
        maintainAspectRatio : false,
        responsive : true,
      }
      //Create pie or doughnut chart
      // You can switch between pie and douhnut using the method below.
      var donutChart = new Chart(donutChartCanvas, {
        type: 'doughnut',
        data: donutData,
        options: donutOptions
      });

          //- DONUT CHART -
      //-------------
      // Get context with jQuery - using jQuery's .get() method.
      var donutChartCanvas2 = $('#donutChart2').get(0).getContext('2d')
      var donutData2        = {
        labels: [
            'Paid',
            'Not Paid',
        ],
        datasets: [
          {
            data: [{{ paid_other }}, {{ unpaid_other }}],
            backgroundColor : ['#7fc9fb', '#dc3545'],
          }
        ]
      }
      var donutOptions2     = {
        maintainAspectRatio : false,
        responsive : true,
      }
      //Create pie or douhnut chart
      // You can switch between pie and douhnut using the method below.
      var donutChart2 = new Chart(donutChartCanvas2, {
        type: 'doughnut',
        data: donutData2,
        options: donutOptions2
      });
    });
  });
  </script>
{% endblock writescript %}

schoolz/templates/users/admin_profile.html
{% extends 'base/base.html' %}
{% block title %} Admin Profile {% endblock title %}

{% block content %}
  <div class="card">
    <div class="card-header">
      <div class="row">
        <img style="height:200px; width:200px; border-radius:50%; margin:auto" src="{{ admin.adminmodel.get_photo_url }}" alt="Photo">
      </div>
    </div>
    <div class="card-body">

      <div class="personal_information">
        <div class="row">
          <h2 class="mx-auto">Admin Information</h2>
        </div>
        <hr>
        <div class="row">
          <div style="font-size:24px; margin-left: 30px">
            {% if user == admin %}
              <p>Username                : <span class="mx-4">{{ admin.username }}</span></p>
            {% endif %}
            <p>Name                    : <span class="mx-4">{{ admin.adminmodel.name }}</span></p>
            <p>Date of Birth           : <span class="mx-4">{{ admin.adminmodel.date_of_birth }}</span></p>
            <p>Section                 : <span class="mx-4">{{ admin.adminmodel.section }}</span></p>
            <p>Mobile No               : <span class="mx-4">{{ admin.adminmodel.mobile }}</span></p>
            <p>Email                   : <span class="mx-4">{{ admin.adminmodel.email }}</span></p>
            <p>Joining Date            : <span class="mx-4">{{ admin.adminmodel.joining_date }}</span></p>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

schoolz/templates/users/admin_signup.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %} Admin {% endblock %}

{% load i18n %}


{% block content %}
<body class="hold-transition login-page">
  <div class="login-box">
    <div class="login-logo">
      <a><b>Admin</b> Signup</a>
    </div>
    <!-- /.login-logo -->
    <div class="card">
      <div class="card-body login-card-body">
        <div class="img-circle img-fluid bg-purple" style="width:70px; margin:auto; margin-bottom:10px; padding:10px;">
          <span style="font-size: 2.5em; color:#89CFF0; " class="fas fa-graduation-cap"></span>
        </div>
         <p class="login-box-msg">{% trans 'Register an Admin.' %}</p>
         <form class="form-horizontal" method="post" enctype="multipart/form-data" action="">
           {% csrf_token %}
           {{ form|crispy }}
           <div class="control-group">
             <div class="controls">
               <button type="submit" class="btn btn-secondary">Sign Up</button>
             </div>
           </div>
         </form>
      </div>
    </div>
  </div>
</body>
{% endblock %}

schoolz/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">
<!--
  <div class="row">
    <div class="col-sm-12">
      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %} -->
<!-- Action buttons -->
  <!--
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    -->
    <!-- Your Stuff: Custom user template urls -->
  <!--
  </div>

</div> -->
<!-- End Action buttons -->
  <!--
{% endif %}

-->
</div>


{% endblock content %}

schoolz/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock %}

schoolz/templates/users/view_message.html
{% extends 'base/base.html' %}
{% block title %} Message {% endblock title %}

{% block content %}
{% if messages %}
   <div class="form-group">
     <div class="col-12">
       {% for message in messages %}
       {% if message.tags == "error" %}
           <div class="alert alert-default-danger alert-dismissible fade show" role="alert" style="margin-top: 10px;">
           {{ message }}
           <button type="button" class="close" data-dismiss="alert" aria-label="Close">
               <span aria-hidden="true">&times;</span>
           </button>
           </div>
       {% elif message.tags == "success" %}
           <div class="alert alert-default-success alert-dismissible fade show" role="alert" style="margin-top: 10px;">
           {{ message }}
           <button type="button" class="close" data-dismiss="alert" aria-label="Close">
               <span aria-hidden="true">&times;</span>
           </button>
           </div>
       {% endif %}
       {% endfor %}
     </div>
   </div>
{% endif %}
{% if message %}
<div class="row">
{% for article in message %}
  <div class="col-md-6">
    <div class="card" >
      <div class="card-header" {% if article.private == True %} style="background-color: #ffac81; background-image: linear-gradient(315deg, #ffac81 0%, #ff928b 74%); color: white" {% else %} style="background-color: #5de6de; background-image: linear-gradient(315deg, #5de6de 0%, #b58ecc 74%); color: white" {% endif %}>
        <h3 class="card-title"> {{ article.title }} <span class="text-muted"><small> -sent by {{ article.admin.name }} to {{ article.teacher.name }} | {{ article.updated_at }} </small> </span></h3>

        <div class="card-tools">
          <button type="button" class="btn btn-tool text-white" data-card-widget="maximize"><i class="fas fa-expand"></i></button>
          <button type="button" class="btn btn-tool text-white" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
          <button type="button" class="btn btn-tool text-white" data-card-widget="remove"><i class="fas fa-times"></i></button>
        </div>
        <!-- /.card-tools -->
      </div>
      <!-- /.card-header -->
      <div class="card-body" style="background-color: #eff1f4">
        {{ article.message }}
      </div>
      <!-- /.card-body -->
      {% if request.user.is_admin %}
      <div class="card-footer" {% if article.private == True %} style="background-color: #ffac81; background-image: linear-gradient(315deg, #ffac81 0%, #ff928b 74%); color: white" {% else %} style="background-color: #5de6de; background-image: linear-gradient(315deg, #5de6de 0%, #b58ecc 74%); color: white" {% endif %}>
        <span class="d-flex justify-content-lg-end">
          <span class="mx-3"><a style="color:white" href="{% url 'users:message_update' article.slug %}?next={{ request.path|urlencode }}" >Edit</a> </span>
          |
          <span class="mx-2"><a style="color:white" href="{% url 'users:message_delete' article.slug %}?next={{ request.path|urlencode }}">Delete</a></span>
        </span>
      </div>
         {% endif %}
    </div>
    <!-- /.card -->

<!-- /.col -->
    <br/>
  </div>
{% endfor %}
</div>
{% else %}
  <p> There are no messages. </p>
{% endif %}
{% endblock %}