config/urls.py
import notifications.urls
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token

from students.views import (
    college_classroom_post_comment,
    college_classroom_post_reply,
    college_student,
    college_student_articles,
    college_student_assignments,
    college_student_classroom_give_test,
    college_student_classroom_view_post,
    college_student_reading_materials,
    college_student_submit_assignment,
    college_student_videos,
    college_teacher_student_account,
    delete_comment_or_reply,
)
from teachers.views import (
    college_teacher_classroom,
    college_teacher_classroom_add_post,
    college_teacher_classroom_delete_test,
    college_teacher_classroom_view_test,
    view_assignments_submissions,
    view_test_performance,
    view_tests_submissions,
)

urlpatterns = [
    path(
        "",
        TemplateView.as_view(
            template_name="home/home.html", extra_context={"section": "home"}
        ),
        name="home",
    ),
    path(
        "profile/",
        TemplateView.as_view(template_name="home/profile.html"),
        name="profile",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("schoolz.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("teachers/", include("teachers.urls")),
    path("students/", include("students.urls")),
    url(
        "^inbox/notifications/", include(notifications.urls, namespace="notifications")
    ),
    path(
        "college/teacher/classroom/",
        college_teacher_classroom,
        name="college_teacher_classroom",
    ),
    path(
        "college/teacher/classroom/<int:pk>/add_post",
        college_teacher_classroom_add_post,
        name="college_teacher_classroom_add_post",
    ),
    path(
        "college/teacher/classroom/view_test/<slug:slug_pk>/",
        college_teacher_classroom_view_test,
        name="college_teacher_classroom_view_test",
    ),
    path(
        "college/teacher/classroom/delete_test/<slug:slug_pk>/",
        college_teacher_classroom_delete_test,
        name="college_teacher_classroom_delete_test",
    ),
    path(
        "college/teacher/classroom/view_tests_submissions/",
        view_tests_submissions,
        name="view_tests_submissions",
    ),
    path(
        "college/teacher/classroom/view_assignments_submissions/",
        view_assignments_submissions,
        name="view_assignments_submissions",
    ),
    path(
        "college/teacher/classroom/view_test_performance/<slug:slug_pk>",
        view_test_performance,
        name="view_test_performance",
    ),
    path("college/student", college_student, name="college_student"),
    path(
        "college/student/classroom/college_student_assignments",
        college_student_assignments,
        name="college_student_assignments",
    ),
    path(
        "college/student/classroom/college_student_submit_assignment/<slug:slug_pk>/",
        college_student_submit_assignment,
        name="college_student_submit_assignment",
    ),
    path(
        "college/student/classroom/college_student_reading_materials",
        college_student_reading_materials,
        name="college_student_reading_materials",
    ),
    path(
        "college/student/classroom/college_student_videos",
        college_student_videos,
        name="college_student_videos",
    ),
    path(
        "college/student/classroom/college_student_articles",
        college_student_articles,
        name="college_student_articles",
    ),
    path(
        "college/student/classroom/give_test/<slug:slug_pk>/",
        college_student_classroom_give_test,
        name="college_student_classroom_give_test",
    ),
    path(
        "college/classroom/view_post/<slug:slug_pk>/",
        college_student_classroom_view_post,
        name="college_student_classroom_view_post",
    ),
    path(
        "college/classroom/comment",
        college_classroom_post_comment,
        name="college_classroom_post_comment",
    ),
    path(
        "college/classroom/reply",
        college_classroom_post_reply,
        name="college_classroom_post_reply",
    ),
    path(
        "college/classroom/delete_comment_or_reply/<int:pk>",
        delete_comment_or_reply,
        name="delete_comment_or_reply",
    ),
    path(
        "college/student/college_teacher_student_account",
        college_teacher_student_account,
        name="college_teacher_student_account",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

schoolz/users/urls.py
from django.urls import path

from .views import (
    AdminDetailView,
    AdminSignUpView,
    AdminUpdateView,
    DeleteMessage,
    UpdateMessage,
    admin_dashboard,
    create_codes,
    load_students,
    send_admin_message,
    send_general_message,
    send_messages,
    show_list,
    user_detail_view,
    user_redirect_view,
    user_update_view,
    view_codes,
    view_messages,
)

app_name = "users"

urlpatterns = [
    path("parent/", send_admin_message, name="parent"),
    path("view_codes/", view_codes, name="view_codes"),
    path("create_codes/", create_codes, name="code"),
    path("load_students/", load_students, name="load"),
    path(
        "<slug:slug_pk>/message_edit/", UpdateMessage.as_view(), name="message_update"
    ),
    path(
        "<slug:slug_pk>/message_delete/", DeleteMessage.as_view(), name="message_delete"
    ),
    path("view_messages/", view_messages, name="view_message"),
    path("send_message/", send_messages, name="message"),
    path("send_general_message/", send_general_message, name="general_message"),
    path("show_list/", show_list, name="show_list"),
    path("dashboard/", admin_dashboard, name="dash"),
    path("<slug:uuid_pk>/profile/", AdminDetailView.as_view(), name="admin_detail"),
    path("<slug:uuid_pk>/update/", AdminUpdateView.as_view(), name="admin_update"),
    path("signup/", AdminSignUpView.as_view(), name="admin"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

students/urls.py
from django.urls import path

from .views import (  # search_student,
    StudentAdminSignupView,
    StudentDeleteView,
    StudentProfileView,
    StudentSignupView,
    StudentTeacherUpdateView,
    StudentUpdateView,
    active,
    load_sub_class,
    payment,
    result_pin,
    search_all,
    show_result,
    student_dashboard,
    student_list,
    student_teacher_list,
    view_general_messages,
    view_messages,
)

app_name = "students"

urlpatterns = [
    path("signup/", StudentSignupView.as_view(), name="signup"),
    path("student_signup/", StudentAdminSignupView.as_view(), name="student_signup"),
    path("<slug:uuid_pk>/profile/", StudentProfileView.as_view(), name="profile"),
    path("<slug:uuid_pk>/edit/", StudentUpdateView.as_view(), name="update"),
    path("<slug:uuid_pk>/update/", StudentTeacherUpdateView.as_view(), name="updates"),
    path("<slug:uuid_pk>/delete/", StudentDeleteView.as_view(), name="delete"),
    path("dashboard/", student_dashboard, name="dash"),
    path("student_list/", student_teacher_list, name="student_teacher_list"),
    path("students_list/", student_list, name="student_list"),
    path("show_result/", show_result, name="show_result"),
    path("load_subclass/", load_sub_class, name="load_subclass"),
    path("view_message/", view_messages, name="message"),
    path("general_message/", view_general_messages, name="general_message"),
    path("find/", search_all, name="search_all"),
    path("payment/", payment, name="payment"),
    path("pin/<int:class_id>/<int:session_id>", result_pin, name="pin"),
    path("<slug:uuid_key>/active/", active, name="active"),
]

teachers/urls.py
from django.urls import path

from .views import (
    AdminTeacherUpdateView,
    DeleteMessage,
    TeacherDeleteView,
    TeacherProfileView,
    TeacherSignupView,
    TeacherUpdateView,
    UpdateMessage,
    add_result,
    load_class,
    load_student_result,
    load_sub_class,
    promote_student,
    promote_student_process,
    send_general_message,
    send_messages,
    show_result,
    show_teachers_comment,
    teacher_dashboard,
    teacher_list,
    teachers_comment,
    view_admin_messages,
    view_general_messages,
    view_messages,
)

app_name = "teachers"

urlpatterns = [
    path("<slug:section>/list/", teacher_list, name="list"),
    path("signup/", TeacherSignupView.as_view(), name="signup"),
    path("<slug:uuid_pk>/edit/", TeacherUpdateView.as_view(), name="update"),
    path(
        "<slug:uuid_pk>/admin_edit/",
        AdminTeacherUpdateView.as_view(),
        name="admin_update",
    ),
    path("<slug:uuid_pk>/profile/", TeacherProfileView.as_view(), name="profile"),
    path("<slug:uuid_pk>/delete/", TeacherDeleteView.as_view(), name="delete"),
    path("dashboard/", teacher_dashboard, name="dash"),
    path("add_result/", add_result, name="add_result"),
    path("show_result/", show_result, name="show_result"),
    path("load_subclass", load_sub_class, name="load_subclass"),
    path("load_class", load_class, name="load_class"),
    path("promote/", promote_student, name="promote"),
    path("process/", promote_student_process, name="promote_student"),
    path("send_message/", send_messages, name="message"),
    path("send_general_message/", send_general_message, name="general_message"),
    path("view_messages/", view_messages, name="view_message"),
    path("view_admin_messages/", view_admin_messages, name="view_admin_message"),
    path("view_general_messages/", view_general_messages, name="view_general_message"),
    path(
        "<slug:slug_pk>/message_edit/", UpdateMessage.as_view(), name="message_update"
    ),
    path(
        "<slug:slug_pk>/message_delete/", DeleteMessage.as_view(), name="message_delete"
    ),
    path("teachers_comment/", teachers_comment, name="teachers_comment"),
    path("load_comment", show_teachers_comment, name="load_comment"),
    path("load_student_result", load_student_result, name="load_student_result"),
]

schoolz/users/forms.py
from django import forms as form
from django.contrib.auth import forms
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.db import transaction
from django.utils.translation import gettext_lazy as _

from teachers.models import Section, TeacherMessages

from .models import Admin, AdminModel

User = get_user_model()


class TeacherMessageForm(form.ModelForm):
    class Meta:
        model = TeacherMessages
        exclude = {"admin", "teacher", "updated_at", "created_at", "private", "slug"}
        widgets = {
            "title": form.TextInput(attrs={"class": "form-control"}),
            "messages": form.TextInput(attrs={"class": "form-control"}),
        }


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    error_message = admin_forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])


class AdminSignUpForm(UserCreationForm):
    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )
    name = form.CharField(
        max_length=150, widget=form.TextInput(attrs={"class": "form-control"})
    )
    photo = form.ImageField(
        required=False, widget=form.ClearableFileInput(attrs={"class": "form-control"})
    )
    date_of_birth = form.DateField(
        required=True, widget=form.TextInput(attrs={"type": "date"})
    )
    section = form.ModelChoiceField(queryset=Section.objects.all(), required=True)

    mobile = form.CharField(
        max_length=11,
        required=True,
        widget=form.TextInput(attrs={"class": "form-control"}),
    )

    address = form.CharField(
        max_length=500, widget=form.Textarea(attrs={"class": "form-control"})
    )

    email = form.CharField(
        max_length=255,
        required=True,
        widget=form.TextInput(attrs={"class": "form-control"}),
    )
    joining_date = form.DateField(
        required=True, widget=form.TextInput(attrs={"type": "date"})
    )

    class Meta(UserCreationForm.Meta):
        model = Admin
        fields = UserCreationForm.Meta.fields + ("email",)
        exclude = ["username"]

    def clean_username(self):
        username = self.cleaned_data["username"]
        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.name = self.cleaned_data.get("name")
        user.save()
        admin = AdminModel.objects.create(
            user=user,
            uuid=user.uuid,
            name=self.cleaned_data.get("name"),
            photo=self.cleaned_data.get("photo"),
            date_of_birth=self.cleaned_data.get("date_of_birth"),
            section=self.cleaned_data.get("section"),
            mobile=self.cleaned_data.get("mobile"),
            email=self.cleaned_data.get("email"),
            address=self.cleaned_data.get("address"),
            joining_date=self.cleaned_data.get("joining_date"),
        )
        admin.save()
        return user

schoolz/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False, methods=["GET"])
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

schoolz/templates/college/college_base.html
{# This is the base template for college pages. #}
{% load static compress %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'images/favicons/favicon2.png' %}">
    <title>{% block title %}  {% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/college_base.css' %}">
    <link href="{% static 'css/project.css' %}" rel="stylesheet" >
    <link href="https://fonts.googleapis.com/css?family=Baloo|Lato:400,700,900" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/3.0.5/css/adminlte.min.css" integrity="sha512-rVZC4rf0Piwtw/LsgwXxKXzWq3L0P6atiQKBNuXYRbg2FoRbSTIY0k2DxuJcs7dk4e/ShtMzglHKBOJxW8EQyQ==" crossorigin="anonymous" />
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous"/>
    {% csrf_token %}
    <script type="text/javascript">
        let user = '{{ request.user }}'
        const csrftoken = document.querySelector('input[name=csrfmiddlewaretoken]').value
    </script>
</head>

<body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed">
  <div class="wrapper">
  	<!--Navbar-->
  	{% include 'college/navbar.html' %}

    {% include 'college/sidebar.html' %}


    {# Main content #}
    <div class="content-wrapper">
      <div class="content-header">
        <div class="container-fluid">
          <!-- modal for sign out -->
          <div class="modal fade" id="modal-danger">
            <div class="modal-dialog">
              <div class="modal-content bg-danger">
                <div class="modal-header">
                  <h4 class="modal-title">Sign Out</h4>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <form method="post" action="{% url 'account_logout' %}">
                  <div class="modal-body">
                      <p>Are you sure you want to sign out?</p>
                      {% csrf_token %}
                        {% if redirect_field_value %}
                          <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
                        {% endif %}
                  </div>
                  <div class="modal-footer justify-content-between">
                    <button type="button" class="btn btn-outline-light" data-dismiss="modal">Close</button>
                    <button class="btn btn-outline-light" type="submit">Sign out</button>
                  </div>
                </form>
              </div>
              <!-- /.modal-content -->
            </div>
            <!-- /.modal-dialog -->
          </div>
           <!-- /.modal -->
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0 text-navy" style="font-family:Georgia">Classroom</h1>
            </div>
            <!-- /.col -->
            <div class="col-sm-6" style="font-family:Georgia">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
                <li class="breadcrumb-item active" style="font-family:Georgia"><a href="{% if request.user.is_teacher %}{% url 'teachers:dash' %}{% else %}{% url 'students:dash' %}{% endif %}">Dashboard</a></li>
                <li class="breadcrumb-item active" style="font-family:Georgia">Classroom</li>
              </ol>
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>

      <section class="content">
      	<div class="container-fluid">
              {% if request.user.is_admin %}
              {# If the user is a college admin #}
              {% block admin-content %}

              {% endblock admin-content %}

          {% elif request.user.is_teacher %}
              {# If the user is a teacher #}
              {% block teacher-content %}

              {% endblock teacher-content %}

          {% elif request.user.is_student %}
              {# If the user is a student #}
              {% block student-content %}

              {% endblock student-content %}

          {% endif %}
        </div>
      </section>
    </div>
      <!--Footer-->
    <footer class="main-footer">
      <strong>Copyright &copy; <a href="#">Ebere God'sfavour</a>.</strong>
      All rights reserved.
      <div class="float-right d-none d-sm-inline-block">
        <b>Powered</b> by <img src="{% static 'home/img/kintergon.png' %}" style="height:2rem; width 100%" class="img-fluid">
      </div>
    </footer>
  </div>

{# Scripts #}
  <!-- jQuery -->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha512-bnIvzh6FU75ZKxp0GXLH9bewza/OIw6dLVh9ICg0gogclmYGguQJWl8U30WpbsGTqbIiAwxTsbe76DErLq5EDQ==" crossorigin="anonymous"></script>
  <!-- AdminLTE App -->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/3.0.5/js/adminlte.min.js" integrity="sha512-++c7zGcm18AhH83pOIETVReg0dr1Yn8XTRw+0bWSIWAVCAwz1s2PwnSj4z/OOyKlwSXc4RLg3nnjR22q0dhEyA==" crossorigin="anonymous"></script>
<!-- Bootstrap 4 -->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.bundle.min.js" integrity="sha512-c4wThPPCMmu4xsVufJHokogA9X4ka58cy9cEYf5t147wSw0Zo43fwdTy/IC0k1oLxXcUlPvWZMnD8be61swW7g==" crossorigin="anonymous"></script>

<script type="text/javascript" src="{% static 'js/Chart.min.js' %}"></script>
{% block user-chart-js %} {% endblock user-chart-js %}

<script type="text/javascript" src="{% static 'js/college_base.js' %}"></script>

<script>
$.navigation = $('nav > ul.nav');
$(document).ready(function($){

    $.navigation.find('a').each(function(){

    var cUrl = String(window.location).split('?')[0];

    if (cUrl.substr(cUrl.length - 1) == '#') {
      cUrl = cUrl.slice(0,-1);
    }

    if ($($(this))[0].href==cUrl) {
      $(this).addClass('active');

      $(this).parents('ul').add(this).each(function(){
        $(this).parent().addClass('menu-open');
        $(this).parent().children('a').addClass('active');
      });
    }
  });
});
</script>

<noscript>This application requires JavaScript to function. Please enable JavaScript in your browser.</noscript>

 {% compress js %}
    <script src="{% static 'notifications/notify.js' %}" type="text/javascript"></script>
{% block college-admin-script %}

{% endblock college-admin-script %}

{% block college-teacher-script %}

{% endblock college-teacher-script %}

{% block college-student-script %}

{% endblock college-student-script %}
{% endcompress %}
<script>
  $("#Notifs").on('click', function(){
    var url = $("#Notifs").attr("href");

    $.ajax({
            url: url,

          });

        });
</script>
<script>
$.navigation = $('nav > ul.nav');
$(document).ready(function($){

    $.navigation.find('a').each(function(){

    var cUrl = String(window.location).split('?')[0];

    if (cUrl.substr(cUrl.length - 1) == '#') {
      cUrl = cUrl.slice(0,-1);
    }

    if ($($(this))[0].href==cUrl) {
      $(this).addClass('active');

      $(this).parents('ul').add(this).each(function(){
        $(this).parent().addClass('menu-open');
        $(this).parent().children('a').addClass('active');
      });
    }
  });
});
</script>
<script>
$(window).on("load", function (){
  $('#preloader').fadeOut();
});

</script>
</body>
</html>

schoolz/templates/college/navbar.html
{% load notifications_tags static %}

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-dark" style="background-color: #1fd1f9; background-image: linear-gradient(315deg, #1fd1f9 0%, #b621fe 74%)">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'home' %}" class="nav-link">Home</a>
      </li>
    </ul>

    <!-- SEARCH FORM -->
    <form class="form-inline ml-3" action="{% url 'students:search_all' %}" method="get">
      <div class="input-group input-group-sm">
        <input class="form-control form-control-navbar" name="q" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-navbar" type="submit">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Notifications Dropdown Menu -->
      {% notifications_unread as unread_count %}
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" id="Notifs" href="{% url 'notifications:mark_all_as_read' %}">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">{{ unread_count }}</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-header">Notifications</span>
          <div class="dropdown-divider"></div>
          {% with request.user.notifications.unread as unread %}
          {% if unread %}
          {% for notifications in unread %}
          <a class="dropdown-item">
            <i class="fas fa-exclamation text-danger mr-2"></i>{{ notifications.verb }}
            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i>{{ notifications.timesince }} ago</p>
          </a>
          <div class="dropdown-divider"></div>
          {% endfor %}
          <a href="#" class="dropdown-item dropdown-footer">Thank you</a>
          {% else %}
          <a class="dropdown-item dropdown-footer">You have no notifications</a>
          {% endif %}
          {% endwith %}
        </div>
      </li>
      {% if request.user.is_teacher %}
      <li class="nav-item dropdown user-menu">
        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
            	<img src="{{ request.user.teachermodel.get_photo_url }}" class="user-image img-fluid img-circle elevation-2" alt="teacher">
              <span class="d-none d-md-inline">{{ request.user.teachermodel.name }}</span>
        </a>
        <ul class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <!-- User image -->
          <li class="user-header bg-primary">
            	<img src="{{ request.user.teachermodel.get_photo_url }}" class="user-image img-fluid img-circle elevation-2" alt="teacher">
            <p>
            		{{ request.user.teachermodel.name }}
            </p>
          </li>
          <!-- Menu Body -->
          <li class="user-body">
            <div class="row">
              <div class="col-4 text-center">
                <a href="{% url 'teachers:update' request.user.uuid %}">Update Profile</a>
              </div>
              <div class="col-4 text-center">
              </div>
              <div class="col-4 text-center">
                <a href="{# {% url 'account_change_password' %} #} #">Change Password?</a>
              </div>
            </div>
            <!-- /.row -->
          </li>
              <!-- Menu Footer-->
          <li class="user-footer">
          	<a class="btn btn-default btn-flat" href="{% url 'teachers:profile' request.user.uuid %}"> Profile</a>
            <button type="button" class="btn btn-danger btn-flat float-right" data-toggle="modal" data-target="#modal-danger">
                  Logout
            </button>
          </li>
        </ul>
      </li>
      {% else %}
      <li class="nav-item dropdown user-menu">
        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
            	<img src="{{ request.user.studentmodel.get_photo_url }}" class="user-image img-fluid img-circle elevation-2" alt="student">
                <span class="d-none d-md-inline">{{ request.user.studentmodel.name }}</span>
        </a>
        <ul class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <!-- User image -->
          <li class="user-header bg-primary">
            	<img src="{{ request.user.studentmodel.get_photo_url }}" class="user-image img-fluid img-circle elevation-2" alt="student">
            <p>
            		{{ request.user.studentmodel.name }}
            </p>
          </li>
          <li class="user-body">
            <div class="row">
              <div class="col-4 text-center">
                <a href="{% url 'account_change_password' %}">Change Password?</a>
              </div>
              <div class="col-4 text-center">
              </div>
              <div class="col-4 text-center">
                <a href="{% url 'students:updates' request.user.uuid %}">Update Profile</a>
              </div>
            </div>
            <!-- /.row -->
          </li>
              <!-- Menu Footer-->
          <li class="user-footer">
          	<a class="btn btn-default btn-flat" href="{% url 'students:profile' request.user.uuid %}">Profile</a>
            <button type="button" class="btn btn-danger btn-flat float-right" data-toggle="modal" data-target="#modal-danger">
                  Logout
            </button>
          </li>
        </ul>
      </li>
      {% endif %}
    </ul>
  </nav>
  <!-- /.navbar -->

  {% block script %}
  {% endblock script %}