config/urls.py
import notifications.urls
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token

from students.views import (
    college_classroom_post_comment,
    college_classroom_post_reply,
    college_student,
    college_student_articles,
    college_student_assignments,
    college_student_classroom_give_test,
    college_student_classroom_view_post,
    college_student_reading_materials,
    college_student_submit_assignment,
    college_student_videos,
    college_teacher_student_account,
    delete_comment_or_reply,
)
from teachers.views import (
    college_teacher_classroom,
    college_teacher_classroom_add_post,
    college_teacher_classroom_delete_test,
    college_teacher_classroom_view_test,
    view_assignments_submissions,
    view_test_performance,
    view_tests_submissions,
)

urlpatterns = [
    path(
        "",
        TemplateView.as_view(
            template_name="home/home.html", extra_context={"section": "home"}
        ),
        name="home",
    ),
    path(
        "profile/",
        TemplateView.as_view(template_name="home/profile.html"),
        name="profile",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("schoolz.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("teachers/", include("teachers.urls")),
    path("students/", include("students.urls")),
    url(
        "^inbox/notifications/", include(notifications.urls, namespace="notifications")
    ),
    path(
        "college/teacher/classroom/",
        college_teacher_classroom,
        name="college_teacher_classroom",
    ),
    path(
        "college/teacher/classroom/<int:pk>/add_post",
        college_teacher_classroom_add_post,
        name="college_teacher_classroom_add_post",
    ),
    path(
        "college/teacher/classroom/view_test/<slug:slug_pk>/",
        college_teacher_classroom_view_test,
        name="college_teacher_classroom_view_test",
    ),
    path(
        "college/teacher/classroom/delete_test/<slug:slug_pk>/",
        college_teacher_classroom_delete_test,
        name="college_teacher_classroom_delete_test",
    ),
    path(
        "college/teacher/classroom/view_tests_submissions/",
        view_tests_submissions,
        name="view_tests_submissions",
    ),
    path(
        "college/teacher/classroom/view_assignments_submissions/",
        view_assignments_submissions,
        name="view_assignments_submissions",
    ),
    path(
        "college/teacher/classroom/view_test_performance/<slug:slug_pk>",
        view_test_performance,
        name="view_test_performance",
    ),
    path("college/student", college_student, name="college_student"),
    path(
        "college/student/classroom/college_student_assignments",
        college_student_assignments,
        name="college_student_assignments",
    ),
    path(
        "college/student/classroom/college_student_submit_assignment/<slug:slug_pk>/",
        college_student_submit_assignment,
        name="college_student_submit_assignment",
    ),
    path(
        "college/student/classroom/college_student_reading_materials",
        college_student_reading_materials,
        name="college_student_reading_materials",
    ),
    path(
        "college/student/classroom/college_student_videos",
        college_student_videos,
        name="college_student_videos",
    ),
    path(
        "college/student/classroom/college_student_articles",
        college_student_articles,
        name="college_student_articles",
    ),
    path(
        "college/student/classroom/give_test/<slug:slug_pk>/",
        college_student_classroom_give_test,
        name="college_student_classroom_give_test",
    ),
    path(
        "college/classroom/view_post/<slug:slug_pk>/",
        college_student_classroom_view_post,
        name="college_student_classroom_view_post",
    ),
    path(
        "college/classroom/comment",
        college_classroom_post_comment,
        name="college_classroom_post_comment",
    ),
    path(
        "college/classroom/reply",
        college_classroom_post_reply,
        name="college_classroom_post_reply",
    ),
    path(
        "college/classroom/delete_comment_or_reply/<int:pk>",
        delete_comment_or_reply,
        name="delete_comment_or_reply",
    ),
    path(
        "college/student/college_teacher_student_account",
        college_teacher_student_account,
        name="college_teacher_student_account",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

schoolz/users/urls.py
from django.urls import path

from .views import (
    AdminDetailView,
    AdminSignUpView,
    AdminUpdateView,
    DeleteMessage,
    UpdateMessage,
    admin_dashboard,
    create_codes,
    load_students,
    send_admin_message,
    send_general_message,
    send_messages,
    show_list,
    user_detail_view,
    user_redirect_view,
    user_update_view,
    view_codes,
    view_messages,
)

app_name = "users"

urlpatterns = [
    path("parent/", send_admin_message, name="parent"),
    path("view_codes/", view_codes, name="view_codes"),
    path("create_codes/", create_codes, name="code"),
    path("load_students/", load_students, name="load"),
    path(
        "<slug:slug_pk>/message_edit/", UpdateMessage.as_view(), name="message_update"
    ),
    path(
        "<slug:slug_pk>/message_delete/", DeleteMessage.as_view(), name="message_delete"
    ),
    path("view_messages/", view_messages, name="view_message"),
    path("send_message/", send_messages, name="message"),
    path("send_general_message/", send_general_message, name="general_message"),
    path("show_list/", show_list, name="show_list"),
    path("dashboard/", admin_dashboard, name="dash"),
    path("<slug:uuid_pk>/profile/", AdminDetailView.as_view(), name="admin_detail"),
    path("<slug:uuid_pk>/update/", AdminUpdateView.as_view(), name="admin_update"),
    path("signup/", AdminSignUpView.as_view(), name="admin"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

students/urls.py
from django.urls import path

from .views import (  # search_student,
    StudentAdminSignupView,
    StudentDeleteView,
    StudentProfileView,
    StudentSignupView,
    StudentTeacherUpdateView,
    StudentUpdateView,
    active,
    load_sub_class,
    payment,
    result_pin,
    search_all,
    show_result,
    student_dashboard,
    student_list,
    student_teacher_list,
    view_general_messages,
    view_messages,
)

app_name = "students"

urlpatterns = [
    path("signup/", StudentSignupView.as_view(), name="signup"),
    path("student_signup/", StudentAdminSignupView.as_view(), name="student_signup"),
    path("<slug:uuid_pk>/profile/", StudentProfileView.as_view(), name="profile"),
    path("<slug:uuid_pk>/edit/", StudentUpdateView.as_view(), name="update"),
    path("<slug:uuid_pk>/update/", StudentTeacherUpdateView.as_view(), name="updates"),
    path("<slug:uuid_pk>/delete/", StudentDeleteView.as_view(), name="delete"),
    path("dashboard/", student_dashboard, name="dash"),
    path("student_list/", student_teacher_list, name="student_teacher_list"),
    path("students_list/", student_list, name="student_list"),
    path("show_result/", show_result, name="show_result"),
    path("load_subclass/", load_sub_class, name="load_subclass"),
    path("view_message/", view_messages, name="message"),
    path("general_message/", view_general_messages, name="general_message"),
    path("find/", search_all, name="search_all"),
    path("payment/", payment, name="payment"),
    path("pin/<int:class_id>/<int:session_id>", result_pin, name="pin"),
    path("<slug:uuid_key>/active/", active, name="active"),
]

teachers/urls.py
from django.urls import path

from .views import (
    AdminTeacherUpdateView,
    DeleteMessage,
    TeacherDeleteView,
    TeacherProfileView,
    TeacherSignupView,
    TeacherUpdateView,
    UpdateMessage,
    add_result,
    load_class,
    load_student_result,
    load_sub_class,
    promote_student,
    promote_student_process,
    send_general_message,
    send_messages,
    show_result,
    show_teachers_comment,
    teacher_dashboard,
    teacher_list,
    teachers_comment,
    view_admin_messages,
    view_general_messages,
    view_messages,
)

app_name = "teachers"

urlpatterns = [
    path("<slug:section>/list/", teacher_list, name="list"),
    path("signup/", TeacherSignupView.as_view(), name="signup"),
    path("<slug:uuid_pk>/edit/", TeacherUpdateView.as_view(), name="update"),
    path(
        "<slug:uuid_pk>/admin_edit/",
        AdminTeacherUpdateView.as_view(),
        name="admin_update",
    ),
    path("<slug:uuid_pk>/profile/", TeacherProfileView.as_view(), name="profile"),
    path("<slug:uuid_pk>/delete/", TeacherDeleteView.as_view(), name="delete"),
    path("dashboard/", teacher_dashboard, name="dash"),
    path("add_result/", add_result, name="add_result"),
    path("show_result/", show_result, name="show_result"),
    path("load_subclass", load_sub_class, name="load_subclass"),
    path("load_class", load_class, name="load_class"),
    path("promote/", promote_student, name="promote"),
    path("process/", promote_student_process, name="promote_student"),
    path("send_message/", send_messages, name="message"),
    path("send_general_message/", send_general_message, name="general_message"),
    path("view_messages/", view_messages, name="view_message"),
    path("view_admin_messages/", view_admin_messages, name="view_admin_message"),
    path("view_general_messages/", view_general_messages, name="view_general_message"),
    path(
        "<slug:slug_pk>/message_edit/", UpdateMessage.as_view(), name="message_update"
    ),
    path(
        "<slug:slug_pk>/message_delete/", DeleteMessage.as_view(), name="message_delete"
    ),
    path("teachers_comment/", teachers_comment, name="teachers_comment"),
    path("load_comment", show_teachers_comment, name="load_comment"),
    path("load_student_result", load_student_result, name="load_student_result"),
]

teachers/models.py
import random
import string
from datetime import timedelta

from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import text, timezone


class Section(models.Model):
    id = models.AutoField(primary_key=True)
    sections = models.CharField(max_length=50)

    def __str__(self):
        return self.sections


class Class(models.Model):
    id = models.AutoField(primary_key=True)
    section = models.ForeignKey(Section, on_delete=models.CASCADE, default=1)
    class_name = models.CharField(max_length=50)

    class Meta:
        ordering = ["pk"]
        verbose_name_plural = "Classes"

    def __str__(self):
        return self.class_name


class SubClass(models.Model):
    id = models.AutoField(primary_key=True)
    class_name = models.ForeignKey(Class, on_delete=models.CASCADE, null=True)
    sub_class = models.CharField(max_length=50)

    class Meta:
        ordering = ["pk"]
        verbose_name_plural = "Subclasses"

    def __str__(self):
        return f"{self.sub_class} of {self.class_name}"


class Session(models.Model):
    id = models.AutoField(primary_key=True)
    session_name = models.CharField(max_length=20)

    class Meta:
        ordering = ["pk"]

    def __str__(self):
        return self.session_name


class TeacherModel(models.Model):
    uuid = models.UUIDField(
        unique=True,
        editable=False,
    )
    user = models.OneToOneField(
        "users.User", on_delete=models.CASCADE, primary_key=True
    )
    name = models.CharField("Full Name", max_length=150)
    photo = models.ImageField(upload_to="teacherfile/", null=True, blank=True)
    date_of_birth = models.DateField(blank=True, null=True)
    section = models.ForeignKey(Section, on_delete=models.SET_NULL, null=True)
    class_name = models.ForeignKey(Class, on_delete=models.SET_NULL, null=True)
    sub_class = models.ForeignKey(SubClass, on_delete=models.SET_NULL, null=True)
    address = models.TextField(null=True, blank=True)
    mobile = models.CharField(max_length=11, blank=True, null=True)
    email = models.CharField(max_length=255, blank=True, null=True)
    joining_date = models.DateField(blank=True, null=True, default=timezone.now)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return "{} ({})".format(self.name, self.class_name)

    @property
    def get_photo_url(self):
        try:
            if self.photo.url:
                return f"{self.photo.url}"
        except Exception:
            return f"{settings.MEDIA_URL}{self.photo}"

    def get_absolute_url(self):
        return reverse("users:dash", args=None)


def rand_slug():
    return "".join(
        random.choice(string.ascii_letters + string.digits) for _ in range(6)
    )


class TeacherMessages(models.Model):
    id = models.AutoField(primary_key=True)
    admin = models.ForeignKey("users.AdminModel", on_delete=models.CASCADE)
    teacher = models.ForeignKey(TeacherModel, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=50)
    message = models.TextField()
    private = models.BooleanField(default=False)
    slug = models.SlugField(blank=True, max_length=255, unique=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]
        verbose_name_plural = "Teacher Messages"

    def __str__(self):
        return f"{self.title}"

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = text.slugify(rand_slug() + "-" + self.title)
        super().save(*args, **kwargs)

    def was_published_recently(self):
        return self.updated_at >= timezone.now() - timedelta(days=30)

schoolz/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False, methods=["GET"])
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

schoolz/templates/student/signup.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %} Student SignUp {% endblock %}
{% load i18n %}


{% block content %}
{{ block.super }}
<body class="hold-transition login-page">
  <div class="login-box">
    <div class="login-logo">
      <a><b>Student</b> Signup Form</a>
    </div>
    <!-- /.login-logo -->
    <div class="card">
      <div class="card-body login-card-body">
        <div class="img-circle img-fluid bg-purple" style="width:70px; margin:auto; margin-bottom:10px; padding:10px;">
          <span style="font-size: 2.5em; color:#89CFF0; " class="fas fa-graduation-cap"></span>
        </div>
         <p class="login-box-msg text-muted">{% trans 'Register a new student.' %}</p>
          {% comment %} Display Messages {% endcomment %}
            {% if messages %}
              <div class="form-group">
                <div class="col-12">
                  {% for message in messages %}
                    {% if message.tags == "error" %}
                      <div class="alert alert-default-danger alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                        {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                    {% elif message.tags == "success" %}
                      <div class="alert alert-default-success alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                        {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                    {% endif %}
                  {% endfor %}
                </div>
              </div>
            {% endif %}

        <form class="form-horizontal" enctype="multipart/form-data" method="post" action="" id="StudentRegistrationForm"  data-class-url={% url 'teachers:load_class' %} data-subclass-url={% url 'students:load_subclass' %}>
          {% csrf_token %}
          {{ form|crispy }}
          {{ forms|crispy }}
          <div class="custom-control custom-checkbox">
            <input type='checkbox' name='more' class='custom-control-input' id="customCheck"/>
            <label class="custom-control-label" for="customCheck"> Save and add more </label>
          </div>
          <div class="control-group">
            <div class="controls">
              <button type="submit" class="btn bg-purple my-5">Sign Up</button>
              <a class="ml-3 ml-md-5" style="color: #fc5f1c" href="{% if user.is_admin %} {% url 'users:dash' %} {% else %} {% url 'teachers:dash' %} {% endif %}">Dashboard &#8954</a>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</body>
{% endblock %}
{% block javascript %}
{{ block.super }}
    <script>
        $("#id_section").change(function () {
          var url = $("#StudentRegistrationForm").attr("data-class-url");
          var SectionId = $(this).val();

          $.ajax({
            url: url,
            data: {
              'section': SectionId
            },
            success: function (data) {
              $("#id_class_name").html(data);
            }
          });

        });

        $("#id_class_name").change(function () {
          var url = $("#StudentRegistrationForm").attr("data-subclass-url");
          var classId = $(this).val();

          $.ajax({
            url: url,
            data: {
              'class': classId
            },
            success: function (data) {
              $("#id_sub_class").html(data);
            }
          });

        });
    </script>
{% endblock javascript %}

schoolz/templates/student/student_delete.html
{% extends 'base/base.html' %}
{% block title %} Delete Student {% endblock title %}
{% load static %}

{% block content %}
<div class="card">
      <div class="card-body login-card-body">
        <h5 class="login-box-msg">Delete</h5>
          <form method="post" action="">
            {% csrf_token %}
            <p> Are you sure you want to delete <b>{{ students.studentmodel.name }}</b>. If you delete {{ students.studentmodel.name }} all <b>data and records of this student will be removed.</b></p>
            <button class="btn btn-danger btn-block" type="submit">Confirm</button>
          </form>
      </div>
</div>
{% endblock %}

schoolz/templates/student/student_list.html
{% extends 'base/base.html' %}
{% block title %} Student List {% endblock title %}

{% block content %}
  <div class="animated fadeIn">
      <div class="card">
          <div class="card-header" style="background-color: #f8ceec; background-image: linear-gradient(315deg, #f8ceec 0%, #a88beb 74%)">
              <h3 class="card-title text-white"> Student Table </h3> <div class="card-tools text-white"><i class="fa fa-edit"></i></div>
          </div>
          <div id="messages">
            {% if messages %}
                <div class="form-group">
                  <div class="col-12">
                    {% for message in messages %}
                    {% if message.tags == "error" %}
                        <div class="alert alert-default-danger alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                        {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        </div>
                    {% elif message.tags == "success" %}
                        <div class="alert alert-default-success alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                        {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        </div>
                    {% endif %}
                    {% endfor %}
                  </div>
                </div>
              {% endif %}
            </div>
          {% if students %}
          <div class="card-body table-responsive p-0">
             <table class="table table-hover text-nowrap table-striped table-bordered">
                 <thead>
                     <tr class="text-gray-dark">
                         <th>Id</th>
                         <th>Name</th>
                         <th>Mobile number</th>
                         <th>Profile</th>
                         <th>Update</th>
                         <th>Paid</th>
                     </tr>
                 </thead>
                 <tbody>
                   {% for students in students %}
                       <tr class="text-gray">
                            <td>{{ forloop.counter }}</td>
                            <td>{{ students.name }}</td>
                            <td>{{ students.emergency_mobile_number }}</td>
                            <td>
                               <a class="btn" style="background-color: #00da5f; color: white" href="{% url 'students:profile' students.uuid %}">
                                   <i class="fa fa-search-plus"></i>
                               </a>
                            </td>
                            {% if request.user.is_teacher %}
                            <td>
                               <a class="btn" style="background-color: #7fc9fb; color: white" href="{% url 'students:updates' students.uuid %}">
                                   <i class="fa fa-edit"></i>
                               </a>
                            </td>
                            <td>
                                {% csrf_token %}
                                <div class="form-group">
                                  <div class="custom-control custom-switch custom-switch-off-danger custom-switch-on-success">
                                    <input type='checkbox' {% if students.paid == True %} checked {% else %} {% endif %} name='{{ students.name }}' class='custom-control-input' id="{{ students.pk }}"/>
                                    <label class="custom-control-label" for="{{ students.pk }}"> Have Paid? </label>
                                  </div>
                                </div>
                            </td>
                         {% endif %}
                       </tr>
                   {% endfor %}
                 </tbody>
             </table>
          </div>
          {% else %}
          <div class="card-body">
              <h3>No Student Found</h3>
          </div>
          {% endif %}
      </div>
    {% if inactive %}
      <div class="card">
        <div class="card-header" style="background-color: #5de6de; background-image: linear-gradient(315deg, #5de6de 0%, #b58ecc 74%); color: white">
            <h3 class="card-title"> Recently Promoted Student Table </h3>
            <div class="card-tools"><i class="fa fa-edit"></i></div>
        </div>

        <div class="card-body table-responsive p-0">
           <table class="table table-hover text-nowrap table-striped table-bordered">
               <thead>
                   <tr class="text-gray-dark">
                       <th>Id</th>
                       <th>Name</th>
                       <th>Mobile number</th>
                       <th>Profile</th>
                       <th>Make Active</th>
                   </tr>
               </thead>
               <tbody>
                 {% for student in inactive %}
                     <tr class="text-gray">
                          <td>{{ forloop.counter }}</td>
                          <td>{{ student.name }}</td>
                          <td>{{ student.emergency_mobile_number }}</td>
                          <td>
                             <a class="btn" style="background-color: #00da5f; color: white" href="{% url 'students:profile' student.uuid %}">
                                 <i class="fa fa-search-plus"></i>
                             </a>
                          </td>
                          {% if request.user.is_teacher %}
                          <td>
                             <a class="btn" style="background-color: #7fc9fb; color: white" href="{% url 'students:active' student.uuid %}">
                                 <i class="fa fa-user"></i>
                             </a>
                          </td>
                       {% endif %}
                     </tr>
                 {% endfor %}
               </tbody>
           </table>
        </div>
        {% endif %}
      </div>
  </div>
{% endblock %}
{% block script %}
    <script>
        $(document).ready(function () {
            {# To send a request back to the backend for appopriate changing of the status of field Paid #}
            $("input[type='checkbox']").change(function () {
                let value = '';
                ($(this).is(":checked")) ? value = "True" : value = "False" ;
                let name = $(this).attr("name");
                let primary_key = $(this).attr("id")
                $.ajax({
                    method: 'POST',
                    headers: {
                        'X-CSRFToken': $("input[name='csrfmiddlewaretoken']").val(),
                    },
                    url: "{% url 'students:payment' %}",
                    data: {
                        'name': name,
                        'value': value,
                        'primary_key': primary_key,
                    },
                    success: function (data) {
                        $("#messages").html(data);
                    }
                });
            });
        });
    </script>
{% endblock script %}

schoolz/templates/student/update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %} Student Update {% endblock %}

{% load i18n %}


{% block content %}
{{ block.super }}
<body class="hold-transition login-page">
  <div class="login-box">
    <div class="login-logo">
      <a><b>Student</b> Update Form</a>
    </div>
    {% if messages %}
      <div class="form-group">
        <div class="col-12">
          {% for message in messages %}
          {% if message.tags == "error" %}
              <div class="alert alert-default-danger alert-dismissible fade show" role="alert" style="margin-top: 10px;">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
              </button>
              </div>
          {% elif message.tags == "success" %}
              <div class="alert alert-default-success alert-dismissible fade show" role="alert" style="margin-top: 10px;">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
              </button>
              </div>
          {% endif %}
          {% endfor %}
        </div>
      </div>
    {% endif %}
    <!-- /.login-logo -->
    <div class="card">
      <div class="card-body login-card-body">
        <div class="img-circle img-fluid bg-purple" style="width:70px; margin:auto; margin-bottom:10px; padding:10px;">
          <span style="font-size: 2.5em; color:#89CFF0; " class="fas fa-graduation-cap"></span>
        </div>
        <p class="login-box-msg text-muted">{% trans 'Update Student.' %}</p>
        <form class="form-horizontal" enctype="multipart/form-data" method="post" action="" id="StudentUpdateForm" data-class-url={% url 'teachers:load_class' %} data-subclass-url={% url 'students:load_subclass' %}>
          {% csrf_token %}
          {{ form|crispy }}
          <div class="control-group">
            <div class="controls">
              <button type="submit" class="btn bg-purple my-5">Update</button>
              <a class="ml-3 ml-md-5" style="color: #fc5f1c" href="{% if user.is_admin %} {% url 'users:dash' %} {% elif user.is_teacher %} {% url 'teachers:dash' %} {% else %} {% url 'students:dash' %} {% endif %}">Dashboard &#8954</a>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</body>
{% endblock %}
{% block javascript %}
    {{ block.super }}
    <script>
        $("#id_section").change(function () {
          let url = $("#StudentUpdateForm").attr("data-class-url");
          let SectionId = $(this).val();

          $.ajax({
            url: url,
            data: {
              'section': SectionId
            },
            success: function (data) {
              $("#id_class_name").html(data);
            }
          });

        });

        $("#id_class_name").change(function () {
          var url = $("#StudentUpdateForm").attr("data-subclass-url");
          var classId = $(this).val();

          $.ajax({
            url: url,
            data: {
              'class': classId
            },
            success: function (data) {
              $("#id_sub_class").html(data);
            }
          });

        });
    </script>

{% endblock javascript %}